### ISSUE TITLE
Unable to build Jenkins 

### ISSUE THREAD

**Issue by jgardezi** [drawmyattention/laravel-jenkins-ci-boilerplate#1]
Hi,

I am new to Jenkins and I have cloned your project and used http://jenkins-php.org/ as a php-tempate for a "New Item".

After creating new Item I have clicked "Build Now" and in console I am getting the following issue 
<code>
phploc-ci:

BUILD FAILED
/var/lib/jenkins/jobs/laravel-jenkins-ci-boilerplate/workspace/build.xml:62: Execute failed: java.io.IOException: Cannot run program "phploc": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at java.lang.Runtime.exec(Runtime.java:617)
    at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:41)
    at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
    at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
</code>

Please let me know which steps I am missing.

Cheers,
Javed

**Comment by amochohan** [comment]
The error states 'Cannot run program `phploc": error=2, No such file or directory`. You don't have the application `phploc` installed on your CI server.

**Comment by jgardezi** [comment]
Thank you, 

I have figured it out. Test it with by installing phploc on my CI server and also using ${basedir}/vendor/bin as well.

Kind regards,
Javed
